apiVersion: v1
kind: Pod
metadata:
  name: s3-writer
  namespace: default
spec:
  # Here the pod is linked to the service account that has write access to S3
  serviceAccountName: s3-access-sa
  containers:
  - name: s3-writer
    image: amazon/aws-cli:latest
    # A note here please make sure that the bucket that was created is the same below:
    command: ["/bin/sh", "-c", "echo 'Hello, S3!' > /tmp/hello.txt && aws s3 cp /tmp/hello.txt s3://pytorch-svw/hello.txt"]